### ISSUE TITLE
Add dependent packages to build navigation meta-package

### ISSUE THREAD

**Issue by at-wat** [seqsense/aports-ros-experimental#9]
- [x] python-wxtools (not provided by official aports)
- [x] eigen (rosdep key needed, backport to 3.7)
- [x] cppunit
- [x] uuid
- [x] bullet (need new aport)
- [x] sdl
- [x] netpbm (need new aport)
- [x] pcl
- [x] python_sip
- [x] graphviz

**Comment by at-wat** [comment]
due to the upstream problem, bullet3 needs to build example to pass the build and test

**Comment by at-wat** [comment]
bullet3/examples/ThirdPartyLibs/ contains annoying pre-built binary libraries.

**Comment by at-wat** [comment]
netpbm contains chaotic licenses. maybe better to use debian or redhat's free version.

**Comment by at-wat** [comment]
handling main netpbm repository is too painful.
https://github.com/chneukirchen/netpbm-mirror/tree/stable looks good replacement.

**Comment by at-wat** [comment]
external dependencies seems satisfied.

**Comment by at-wat** [comment]
```yaml
build-order:
- catkin
- cmake_modules
- cpp_common
- genmsg
- gennodejs
- genpy
- orocos_kdl
- python_orocos_kdl
- ros_environment
- rosclean
- rosgraph
- roslang
- rosmaster
- rospack
- rosparam
- rostime
- smclib
- xmlrpcpp
- bfl
- class_loader
- gencpp
- geneus
- genlisp
- message_generation
- roscpp_traits
- roslib
- rosunit
- angles
- roscpp_serialization
- roslz4
- message_runtime
- rosbag_storage
- rosbuild
- rosconsole
- std_msgs
- std_srvs
- actionlib_msgs
- bond
- geometry_msgs
- move_base_msgs
- nav_msgs
- pluginlib
- rosgraph_msgs
- tf2_msgs
- visualization_msgs
- roscpp
- rosout
- rospy
- tf2
- tf2_eigen
- tf2_py
- voxel_grid
- bondcpp
- nodelet
- roslaunch
- rostest
- topic_tools
- map_server
- message_filters
- rosbag
- rosmsg
- rosservice
- rostopic
- sensor_msgs
- dynamic_reconfigure
- map_msgs
- nodelet_topic_tools
- pcl_msgs
- rosnode
- roswtf
- actionlib
- pcl_conversions
- tf2_ros
- tf
- tf2_geometry_msgs
- amcl
- fake_localization
- laser_geometry
- pcl_ros
- robot_pose_ekf
- costmap_2d
- nav_core
- navfn
- base_local_planner
- carrot_planner
- clear_costmap_recovery
- dwa_local_planner
- global_planner
- move_slow_and_clear
- rotate_recovery
- move_base
- navigation
```

**Comment by at-wat** [comment]
```
[ 75%] Building CXX object CMakeFiles/tf2.dir/src/static_cache.cpp.o
/tmp/ros/kinetic/tf2/src/src/tf2/src/buffer_core.cpp: In member function 'bool tf2::BufferCore::warnFrameId(const char*, const string&) const':
/tmp/ros/kinetic/tf2/src/src/tf2/src/buffer_core.cpp:126:34: error: 'logWarn' was not declared in this scope
     logWarn("%s",ss.str().c_str());
                                  ^
/tmp/ros/kinetic/tf2/src/src/tf2/src/buffer_core.cpp:134:34: error: 'logWarn' was not declared in this scope
     logWarn("%s",ss.str().c_str());
                                  ^
```

**Comment by at-wat** [comment]
console_bridge version should be rollbacked

**Comment by at-wat** [comment]
```
>>> ros-kinetic-tf2*: Tracing dependencies...
>>> ERROR: ros-kinetic-tf2*: librostime.so: path not found
```

**Comment by at-wat** [comment]
navigation build succeeded
